#!/bin/bash
set -euo pipefail

ROOT="$(cd "$(dirname "$0")" && pwd)"
OUT="$ROOT/bin"
GEN="$OUT/EmbeddedShader.swift"
mkdir -p "$OUT"

if ! command -v xcrun >/dev/null 2>&1; then
  echo "CursorTrail: xcrun is required. Install Xcode Command Line Tools with: xcode-select --install" >&2
  exit 1
fi

if ! xcrun --find swiftc >/dev/null 2>&1; then
  echo "CursorTrail: swiftc is missing. Install/update Xcode Command Line Tools." >&2
  exit 1
fi

SDK="$(xcrun --sdk macosx --show-sdk-path)"
SHADER_B64="$(base64 < "$ROOT/Trail.metal" | tr -d '\n')"

cat > "$GEN" <<SWIFT
// Generated by build.sh from Trail.metal. Do not edit.
import Foundation

enum EmbeddedShader {
    private static let base64 = "$SHADER_B64"

    static let source: String = {
        guard let data = Data(base64Encoded: base64),
              let source = String(data: data, encoding: .utf8) else {
            fatalError("CursorTrail: embedded Metal shader is invalid")
        }
        return source
    }()
}
SWIFT

xcrun swiftc \
  -O \
  -whole-module-optimization \
  -parse-as-library \
  -sdk "$SDK" \
  "$ROOT/main.swift" "$ROOT/TrailModes.swift" "$ROOT/TrailRenderer.swift" "$GEN" \
  -framework AppKit \
  -framework Metal \
  -framework QuartzCore \
  -o "$OUT/cursortrail"

strip -x "$OUT/cursortrail" || true
printf 'Built: %s\n' "$OUT/cursortrail"
printf 'Metal shader embedded in executable (%s bytes source).\n' "$(wc -c < "$ROOT/Trail.metal" | tr -d ' ')"
